### ISSUE TITLE
trigger sound effect when no action can be performed

### ISSUE THREAD

**Issue by ThomasChr** [EndlessVoyage/endlessVoyage#2]

**Comment by PyDario** [comment]
Can you please describe the problem in proper English? I'm not sure whether the sound disappears when pressing the action button or if nothing happens at all.

**Comment by ThomasChr** [comment]
If you use the action key but there is nothing to be done at the actual location there should be a sound indicating that. Something like "möööp".

So we need that sound. Or maybe not? But it‘s a low hanging fruit and will make the game more obvious.

**Comment by Bennyyuke** [comment]
.
