### ISSUE TITLE
Grab Fire Extinguisher with Action key, not just by walking over it

### ISSUE THREAD

**Issue by ThomasChr** [EndlessVoyage/endlessVoyage#3]

**Comment by PyDario** [comment]
We should discuss this together, as I don't personally think this is necessary.

**Comment by ThomasChr** [comment]
It‘s up for discussion. I personally find it a little less easy if you get used to finding the things and then graping them willingly, instead of just walking around and looking what will pop up in your hand. And at the moment a little less easy is what the game needs, in my opinion.

Also if we have more then one item any time you can decide which one you pick up.

**Comment by ThomasChr** [comment]
Pro: 
Thomas
Janic
Benny
Anja

Con:
Dario

No opinion:
Sara

-> So we change that. But not right now because it's not that important!
